dataset: blender
batching: single_image
factor: 0
# num_coarse_samples: 64
# num_fine_samples: 128
use_viewdirs: true
white_bkgd: true
batch_size: 4096
randomized: true

chunk: 4000
len_inpc_train: 200000
len_inpc_eval: 400000
len_inpf_train: 0
len_inpf_eval: 0
