dataset: llff
batching: all_images
num_coarse_samples: 64
num_fine_samples: 128
use_viewdirs: true
white_bkgd: false
batch_size: 4096
randomized: true
near: 0.
far: 1.
factor: 4
llffhold: 8
noise_std: 1.
